context:
  version: "1.0.3"

package:
  name: rslib
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@rslib/core/-/core-${{ version }}.tgz
  sha256: b9348a49d6299c0c769e3646efa35695e8734a2c50443f443f333718ac375188

build:
  number: 0
  noarch: generic

requirements:
  host:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - rslib --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: The Rsbuild-based library development tool.
  homepage: https://lib.rsbuild.dev
  repository: https://github.com/web-infra-dev/rslib

extra:
  recipe-maintainers:
    - danielnachun
