context:
  version: "0.19.2"

package:
  name: rslib
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@rslib/core/-/core-${{ version }}.tgz
  sha256: d60ee69bb55bd42904acd89eb0bee02f00f791e8e4629d149af3cc1c77e6d300

build:
  number: 0
  noarch: generic

requirements:
  host:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - rslib --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: The Rsbuild-based library development tool.
  homepage: https://lib.rsbuild.dev
  repository: https://github.com/web-infra-dev/rslib

extra:
  recipe-maintainers:
    - danielnachun
