context:
  version: "0.21.4"

package:
  name: rslib
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@rslib/core/-/core-${{ version }}.tgz
  sha256: de31a9a73bb26cce8daf1b71d6b89eb430869acee2e792ec0f40f73941de8332

build:
  number: 0
  noarch: generic

requirements:
  host:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - rslib --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: The Rsbuild-based library development tool.
  homepage: https://lib.rsbuild.dev
  repository: https://github.com/web-infra-dev/rslib

extra:
  recipe-maintainers:
    - danielnachun
