context:
  version: "0.16.1"

package:
  name: rslib
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@rslib/core/-/core-${{ version }}.tgz
  sha256: 57335ef00eea13d62973639eadfb043caed3a20e174fb83975f6e54fcc59d83c

build:
  number: 0
  noarch: generic

requirements:
  host:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - rslib --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: The Rsbuild-based library development tool.
  homepage: https://lib.rsbuild.dev
  repository: https://github.com/web-infra-dev/rslib

extra:
  recipe-maintainers:
    - danielnachun
