context:
  version: "0.18.1"

package:
  name: rslib
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/@rslib/core/-/core-${{ version }}.tgz
  sha256: fc2f4f20c229b83bf4869a7ce0183e7911300f9efa994096c7a9962602eda8c2

build:
  number: 0
  noarch: generic

requirements:
  host:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - rslib --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: The Rsbuild-based library development tool.
  homepage: https://lib.rsbuild.dev
  repository: https://github.com/web-infra-dev/rslib

extra:
  recipe-maintainers:
    - danielnachun
